### ISSUE TITLE
Are there some steps not mentioned in ReadMe?

### ISSUE THREAD

**Issue by jianyu4869** [karnwatcharasupat/spauq#5]
Hi, I am now working in miniconda environment in windows with python=3.9. I successfully finished the pip install as mentioned, but at least the program usage meets a problem: 

Traceback (most recent call last):
  File "D:\Users\012875\surroundpy-main\code\spauq.py", line 1, in <module>
    from spauq.core.metrics import spauq_eval
  File "D:\Users\012875\surroundpy-main\code\spauq.py", line 1, in <module>
    from spauq.core.metrics import spauq_eval
ModuleNotFoundError: No module named 'spauq.core'; 'spauq' is not a package

Do you have any ideas about this?

By the way, I would like to know what exactly a reference and estimate video should be?

Thank you in advance

**Comment by jianyu4869** [comment]
Update: I notice that in decomposition.py, after using soundfile.read for audio data, you take data.shape[0] as n_chan, while data.shape[1] as n_sampl. Is it correct? 

I find this in the document of soundfile: "A two-dimensional NumPy (frames x channels) array is returned."
